#!/bin/sh

# look for it in /root/bhyve-patch
PATCH=/root/bhyve-patch/bhyve.patch
if [ ! -f $PATCH ]; then
  echo "No such file or directory: $PATCH"
  exit 1
fi

cd /usr/src
patch </root/bhyve-patch/bhyve.patch && cd /usr/src/usr.sbin/bhyve && make && make install
# from commands executed as part of /usr/src/share/examples for bhybe
install -v -d -m 0755 -o root -g wheel /usr/share/examples/bhyve
install -v -o root -g wheel -m 444 /usr/src/share/examples/bhyve/vmrun.sh /usr/share/examples/bhyve/vmrun.sh
